# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxyman.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proxyman.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproxyman.proto\x12\x19xray.app.proxyman.command\"V\n\x10\x41\x64\x64UserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x33\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0b\x32\".xray.app.proxyman.command.Account\"$\n\x13RemoveUserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"X\n\x0e\x41\x64\x64UserRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x39\n\x04user\x18\x02 \x01(\x0b\x32+.xray.app.proxyman.command.AddUserOperation\"\x11\n\x0f\x41\x64\x64UserResponse\"/\n\x11RemoveUserRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x14\n\x12RemoveUserResponse\"&\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0c\x32\xe1\x01\n\x0eHandlerService\x12\x62\n\x07\x41\x64\x64User\x12).xray.app.proxyman.command.AddUserRequest\x1a*.xray.app.proxyman.command.AddUserResponse\"\x00\x12k\n\nRemoveUser\x12,.xray.app.proxyman.command.RemoveUserRequest\x1a-.xray.app.proxyman.command.RemoveUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxyman_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDUSEROPERATION']._serialized_start=45
  _globals['_ADDUSEROPERATION']._serialized_end=131
  _globals['_REMOVEUSEROPERATION']._serialized_start=133
  _globals['_REMOVEUSEROPERATION']._serialized_end=169
  _globals['_ADDUSERREQUEST']._serialized_start=171
  _globals['_ADDUSERREQUEST']._serialized_end=259
  _globals['_ADDUSERRESPONSE']._serialized_start=261
  _globals['_ADDUSERRESPONSE']._serialized_end=278
  _globals['_REMOVEUSERREQUEST']._serialized_start=280
  _globals['_REMOVEUSERREQUEST']._serialized_end=327
  _globals['_REMOVEUSERRESPONSE']._serialized_start=329
  _globals['_REMOVEUSERRESPONSE']._serialized_end=349
  _globals['_ACCOUNT']._serialized_start=351
  _globals['_ACCOUNT']._serialized_end=389
  _globals['_HANDLERSERVICE']._serialized_start=392
  _globals['_HANDLERSERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
