# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x16xray.app.stats.command\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\">\n\x10GetStatsResponse\x12*\n\x04stat\x18\x01 \x01(\x0b\x32\x1c.xray.app.stats.command.Stat\"3\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"@\n\x12QueryStatsResponse\x12*\n\x04stat\x18\x01 \x03(\x0b\x32\x1c.xray.app.stats.command.Stat\"\x11\n\x0fSysStatsRequest\"\xb5\x01\n\x10SysStatsResponse\x12\x15\n\rnum_goroutine\x18\x01 \x01(\r\x12\x12\n\nnum_thread\x18\x02 \x01(\r\x12\r\n\x05\x61lloc\x18\x03 \x01(\r\x12\x13\n\x0btotal_alloc\x18\x04 \x01(\r\x12\x0b\n\x03sys\x18\x05 \x01(\r\x12\x0f\n\x07mallocs\x18\x06 \x01(\r\x12\r\n\x05\x66rees\x18\x07 \x01(\r\x12\x14\n\x0clive_objects\x18\x08 \x01(\x04\x12\x0f\n\x07up_time\x18\t \x01(\r2\xb7\x02\n\x0cStatsService\x12_\n\x08GetStats\x12\'.xray.app.stats.command.GetStatsRequest\x1a(.xray.app.stats.command.GetStatsResponse\"\x00\x12\x65\n\nQueryStats\x12).xray.app.stats.command.QueryStatsRequest\x1a*.xray.app.stats.command.QueryStatsResponse\"\x00\x12_\n\x08SysStats\x12\'.xray.app.stats.command.SysStatsRequest\x1a(.xray.app.stats.command.SysStatsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSTATSREQUEST']._serialized_start=39
  _globals['_GETSTATSREQUEST']._serialized_end=85
  _globals['_STAT']._serialized_start=87
  _globals['_STAT']._serialized_end=122
  _globals['_GETSTATSRESPONSE']._serialized_start=124
  _globals['_GETSTATSRESPONSE']._serialized_end=186
  _globals['_QUERYSTATSREQUEST']._serialized_start=188
  _globals['_QUERYSTATSREQUEST']._serialized_end=239
  _globals['_QUERYSTATSRESPONSE']._serialized_start=241
  _globals['_QUERYSTATSRESPONSE']._serialized_end=305
  _globals['_SYSSTATSREQUEST']._serialized_start=307
  _globals['_SYSSTATSREQUEST']._serialized_end=324
  _globals['_SYSSTATSRESPONSE']._serialized_start=327
  _globals['_SYSSTATSRESPONSE']._serialized_end=508
  _globals['_STATSSERVICE']._serialized_start=511
  _globals['_STATSSERVICE']._serialized_end=822
# @@protoc_insertion_point(module_scope)
